name = "PowerFlowData"
uuid = "dd99e9e3-7471-40fc-b48d-a10501125371"
authors = "Nick Robinson <npr251@gmail.com> and contributors"
version = "1.3.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataFrames = "1"
DocStringExtensions = "0.8.5"
InlineStrings = "1.1.2"
Parsers = "2.2.1"
PrettyTables = "1"
Tables = "1"
julia = "1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "InteractiveUtils", "Test"]
