name = "PowerFlowData"
uuid = "dd99e9e3-7471-40fc-b48d-a10501125371"
authors = "Nick Robinson <npr251@gmail.com> and contributors"
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataFrames = "1"
DocStringExtensions = "0.8.5"
Parsers = "2"
Tables = "1"
julia = "1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "Test"]
